version: v2

global:
  runner:
    os_image: ubuntu
  variables:
    - RACK_ENV=test

tasks:
  build-docker-image:
    steps:
      - checkout
      - docker/build:
          image: sravanibikkina/node
          dockerfile: Dockerfile
          context: .
  login-to-dockerhub:
     steps:
       - docker login:
           command: 
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  push-to-dockerhub:
      - docker/push:
          image: sravanibikkina/node
          command:
           - docker push sravanibikkina/node:latest
       
