version: v2

global:
  runner:
    os_image: ubuntu
  variables:
    - RACK_ENV=test

tasks:
  build-docker-image:
    steps:
      - checkout
      - docker/build:
          image: sravanibikkina/node
          dockerfile: Dockerfile
          context: .
  push-to-dockerhub:
     steps:
       - docker/push:
           image: sravanibikkina/node
           command:
           - docker login
           - docker push sravanibikkina/node:latest
